In [1]:
import torch
import numpy
import pandas as pd
import matplotlib.pyplot as plt

Tensor Manipulation
1.Addition
2.Subtraciton
3.Multiplication (Element-Wise)
4.Division
5.Matrix Multiplication

In [4]:
#Addition
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.tensor([7,8,9,10])
print(t1+10)
print(t1+t2)
#print(t1+t3) #Error due to different sizes

tensor([11, 12, 13])
tensor([5, 7, 9])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [3]:
#Multiplication
print(t1*10) #Multiplies each element by 10
print(t1*t2) #Multuplies each element by it's corresponding element

tensor([10, 20, 30])
tensor([ 4, 10, 18])
