<a href="https://colab.research.google.com/github/AnasR1/ML-Pytorch/blob/main/PytorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Multiplication using matricies
t1 = torch.tensor([3,4,5])
t2 = torch.tensor([3,4,5])

print(f"element wise multiplication: \n{t1*t2}")
print(f"Matrix Multiplication: \n{torch.matmul(t1,t2)}")

element wise multiplication: 
tensor([ 9, 16, 25])
Matrix Multiplication: 
50


In [ ]:
##Changing Shapes to fit matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
print(tensor_A.shape)
print(tensor_B.shape)
# Transposing a matrix may help
tensor_B = tensor_B.T
tensor_B, tensor_B.shape

tensor_C = torch.matmul(tensor_A, tensor_B)
print(tensor_C, tensor_C.shape)

tensor_D = torch.matmul(tensor_B, tensor_A)
print(tensor_D, tensor_D.shape)
tensor_E = torch.rand(2,3,4,5)
print(tensor_E.shape)
tensor_E = tensor_E.T
print(tensor_E.shape)

torch.Size([3, 2])
torch.Size([3, 2])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) torch.Size([3, 3])
tensor([[ 76, 100],
        [103, 136]]) torch.Size([2, 2])
torch.Size([2, 3, 4, 5])
torch.Size([5, 4, 3, 2])


In [ ]:
#Tensor Aggregation
T1 = torch.arange(0,100,10)
print(T1)
print(f"Min: {T1.min()}")
print(f"Max: {T1.max()}")
print(f"Mean: {T1.type(torch.float32).mean()}")
print(f"Sum: {T1.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Min: 0
Max: 90
Mean: 45.0
Sum: 450


In [36]:
print(T1)
print(T1.argmin())
print(T1.argmax())
print(T1[T1.argmin()])
print(T1[T1.argmax()])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(9)
tensor(0)
tensor(90)


In [43]:
#Reshaping, Stacking, (Un)Squeezing
#Reshaping - reshapes input tensor to defined shape
#View - Returns a view of an input tensor of certain shape but keeps
#same memory as orginal tensor
#Stacking - Combine multiple tensors (vstack [on top of each other]) or
#side by side (hstack)
#Squeeze - removes all 1 dimensions from a tensor
#Unqqueeze - adds a 1 dimension to a tensor
#Permute - Return a view of the input with dimensions permuted(swapped) in a
#defined way

#adding a dimension with reshape: Must have suffiecint elements
x = torch.arange(1.,11.) # 10 Elements
x_reshaped = x.reshape(2,5) # 2x5 needs 10 elements
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(1,10)
print(x_reshaped, x_reshaped.shape)


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) torch.Size([2, 5])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [44]:
#Changing the view
z = x.view(1,10)
print(z, z.shape)
z[:,0] = 5 #changing z changes x as they share the same memory simply new pointer
print(z, x)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [46]:
#Stacking Tensors
x_stacked = torch.stack([x,x,x,x], dim=0) #Vstack as dim = 0
print(x_stacked)
x_stacked = torch.stack([x,x,x,x], dim=1) #Hstack as dim = 1
print(x_stacked)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


In [ ]:
#Squeezing